INSERT INTO products (id, name, subtitle, category, image_url, current_price, original_price, discount, weight, is_organic, is_sale, is_active, created_at) VALUES
('v1', 'Organic Carrots', 'Fresh Organic', 'vegetables', 'assets/images/products/v1.jpg', 230.0, 290.0, '20% OFF', '500g', true, false, true, CURRENT_TIMESTAMP),
('v2', 'Vine Tomatoes', 'Fresh Organic', 'vegetables', 'assets/images/products/v2.jpg', 324.0, 399.0, '18% OFF', '1 kg', true, false, true, CURRENT_TIMESTAMP),
('v3', 'Baby Spinach', 'Fresh Organic', 'vegetables', 'assets/images/products/v3.jpg', 266.0, 320.0, '16% OFF', '200g', true, false, true, CURRENT_TIMESTAMP),
('v4', 'Sweet Corn', 'Fresh Organic', 'vegetables', 'assets/images/products/v4.jpg', 158.0, 208.0, '24% OFF', '1 pc', true, false, true, CURRENT_TIMESTAMP),
('v5', 'Red Onions', 'Fresh Organic', 'vegetables', 'assets/images/products/v5.jpg', 183.0, 232.0, '21% OFF', '1 kg', true, false, true, CURRENT_TIMESTAMP),
('v6', 'Bell Peppers Mix', 'Fresh Organic', 'vegetables', 'assets/images/products/v6.jpg', 374.0, 482.0, '22% OFF', '3 pcs', true, false, true, CURRENT_TIMESTAMP),
('v7', 'Broccoli Head', 'Fresh Organic', 'vegetables', 'assets/images/products/v7.jpg', 291.0, 349.0, '16% OFF', '1 pc', true, true, true, CURRENT_TIMESTAMP),
('v8', 'Cucumber', 'Fresh Organic', 'vegetables', 'assets/images/products/v8.jpg', 149.0, 190.0, '21% OFF', '1 pc', true, false, true, CURRENT_TIMESTAMP),
('v9', 'Zucchini', 'Fresh Organic', 'vegetables', 'assets/images/products/v9.jpg', 241.0, 299.0, '19% OFF', '500g', true, false, true, CURRENT_TIMESTAMP),
('v10', 'Cherry Tomatoes', 'Fresh Organic', 'vegetables', 'assets/images/products/v10.jpg', 349.0, 415.0, '15% OFF', '250g', true, false, true, CURRENT_TIMESTAMP),
('f1', 'Alphonso Mango', 'Fresh Organic', 'fruits', 'assets/images/products/f1.jpg', 996.0, 1245.0, '19% OFF', '3 pcs', true, false, true, CURRENT_TIMESTAMP),
('f2', 'Fresh Bananas', 'Fresh Organic', 'fruits', 'assets/images/products/f2.jpg', 266.0, 332.0, '19% OFF', '1 bunch', true, false, true, CURRENT_TIMESTAMP),
('f3', 'Dragon Fruit', 'Fresh Organic', 'fruits', 'assets/images/products/f3.jpg', 623.0, 813.0, '23% OFF', '1 pc', true, false, true, CURRENT_TIMESTAMP),
('f4', 'Green Apples', 'Fresh Organic', 'fruits', 'assets/images/products/f4.jpg', 482.0, 598.0, '19% OFF', '1 kg', true, false, true, CURRENT_TIMESTAMP),
('f5', 'Papaya', 'Fresh Organic', 'fruits', 'assets/images/products/f5.jpg', 457.0, 581.0, '21% OFF', '1 kg', true, false, true, CURRENT_TIMESTAMP),
('b1', 'Cold-Pressed Juice Mix', 'Fresh Organic', 'beverages', 'assets/images/products/b1.jpg', 739.0, 913.0, '19% OFF', '500ml', true, false, true, CURRENT_TIMESTAMP),
('b2', 'Coconut Water', 'Fresh Organic', 'beverages', 'assets/images/products/b2.jpg', 374.0, 482.0, '22% OFF', '500ml', true, false, true, CURRENT_TIMESTAMP),
('b3', 'Turmeric Latte Mix', 'Fresh Organic', 'beverages', 'assets/images/products/b3.jpg', 739.0, 913.0, '19% OFF', '200g', true, false, true, CURRENT_TIMESTAMP),
('g1', 'Basmati Rice', 'Premium Quality', 'groceries', 'assets/images/products/g1.jpg', 813.0, 1038.0, '21% OFF', '2 kg', false, false, true, CURRENT_TIMESTAMP),
('g2', 'Cold-Pressed Coconut Oil', 'Premium Quality', 'groceries', 'assets/images/products/g2.jpg', 1204.0, 1494.0, '19% OFF', '500ml', false, false, true, CURRENT_TIMESTAMP),
('g3', 'Garlic Bulbs', 'Premium Quality', 'groceries', 'assets/images/products/g3.jpg', 324.0, 415.0, '21% OFF', '250g', false, false, true, CURRENT_TIMESTAMP),
('g4', 'Free Range Eggs', 'Premium Quality', 'groceries', 'assets/images/products/g4.jpg', 540.0, 664.0, '18% OFF', '12 pcs', false, false, true, CURRENT_TIMESTAMP),
('g5', 'Moringa Powder', 'Premium Quality', 'groceries', 'assets/images/products/g5.jpg', 913.0, 1162.0, '21% OFF', '150g', false, false, true, CURRENT_TIMESTAMP);
