server:
  port: ${PORT:8080}
spring:
  application:
    name: vpnexues-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
    username: ${DB_USERNAME:postgres.ufaqrdgppeikmafynbie}
    password: ${DB_PASSWORD:VPNexues05*}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
jwt:
  secret: ${JWT_SECRET:hAGq+0wdcZvn0HVPYGopOoEkBg1G1pw1Xf/bD2ifJCg=}
  expiration: 86400000
app:
  email:
    from: ${APP_EMAIL_FROM:noreply@vpnexues.com}
